In [11]:
import numpy as np

#одномерный массив
a = np.array([1, 2, 3, 4, 5, 6, 8, 9 ])
print(a)

#каждое число умножить на 2
a1 = a * 2 
print(a1)

#нулевой массив
a2 = np.zeros((3, 3))
print(a2)

#массив от 0-19
a3 = np.arange(20)
print(a3)

#первый элемент массива
a4 = a[0]
print(a4)

#тоже самое что и выше, но двухмерное
a5 = np.array([[10, 20, 30],
               [40, 50, 60],
               [70, 80, 90]])
a6 = a5[1, 2]
print(a6)

#среднее значение двухмерного массива
a7 = np.mean(a5)
print(a7)

#каждое число умножить на 2
a8 = a * 2 
print(a8)


#сумма чисел
summ = np.sum(a)
print(summ)

[1 2 3 4 5 6 8 9]
[ 2  4  6  8 10 12 16 18]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
1
60
50.0
[ 2  4  6  8 10 12 16 18]
38
