In [1]:
import numpy as np

#одномерный массив
a = np.array([1, 2, 3, 4, 5, 6, 8, 9 ])
print(a)

#каждое число умножить на 2
a1 = a * 2 
print(a1)

#нулевой массив
a2 = np.zeros((3, 3))
print(a2)

#массив от 0-19
a3 = np.arange(20)
print(a3)

#первый элемент массива
a4 = a[0]
print(a4)

#тоже самое что и выше, но двухмерное
a5 = np.array([[10, 20, 30],
               [40, 50, 60],
               [70, 80, 90]])
a6 = a5[1, 2]
print(a6)

#среднее значение двухмерного массива
a7 = np.mean(a5)
print(a7)

#каждое число умножить на 2
a8 = a * 2 
print(a8)

#сумма чисел
summ = np.sum(a)
print(summ)

# ==========================================
# Примеры использования функций shape и dtype
# ==========================================

# Функция shape возвращает размерность массива (количество элементов по каждой оси)
# Для одномерного массива a:
shape_a = a.shape  # вернет (8,) - массив из 8 элементов
print(f"\nФорма массива a: {shape_a}")

# Для двухмерного массива a5:
shape_a5 = a5.shape  # вернет (3, 3) - 3 строки и 3 столбца
print(f"Форма массива a5: {shape_a5}")

# Для трехмерного массива (создадим для примера):
a9 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
shape_a9 = a9.shape  # вернет (2, 2, 2) - 2 блока, каждый 2x2
print(f"Форма трехмерного массива a9: {shape_a9}")

# Функция dtype возвращает тип данных элементов массива
# Для целочисленного массива a:
dtype_a = a.dtype  # вернет int64 (зависит от системы)
print(f"\nТип данных массива a: {dtype_a}")

# Для массива с плавающей точкой:
a10 = np.array([1.5, 2.7, 3.1])
dtype_a10 = a10.dtype  # вернет float64
print(f"Тип данных массива a10: {dtype_a10}")

# Для массива с другим типом данных:
a11 = np.array([1, 2, 3], dtype=np.float32)  # явно задаем тип float32
dtype_a11 = a11.dtype  # вернет float32
print(f"Тип данных массива a11: {dtype_a11}")

# Можно также создавать массивы с определенным типом данных:
a12 = np.zeros((2, 3), dtype=np.int16)  # массив нулей типа int16
print(f"\nМассив a12 с типом данных {a12.dtype}:")
print(a12)

# Проверка типа данных:
is_int = np.issubdtype(a.dtype, np.integer)  # True, так как a содержит целые числа
is_float = np.issubdtype(a10.dtype, np.floating)  # True, так как a10 содержит числа с плавающей точкой
print(f"\nМассив a содержит целые числа: {is_int}")
print(f"Массив a10 содержит числа с плавающей точкой: {is_float}")

# Пример использования shape и dtype вместе:
print(f"\nСводная информация о массивах:")
print(f"Массив a: shape={a.shape}, dtype={a.dtype}")
print(f"Массив a5: shape={a5.shape}, dtype={a5.dtype}")
print(f"Массив a10: shape={a10.shape}, dtype={a10.dtype}")

[1 2 3 4 5 6 8 9]
[ 2  4  6  8 10 12 16 18]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
1
60
50.0
[ 2  4  6  8 10 12 16 18]
38

Форма массива a: (8,)
Форма массива a5: (3, 3)
Форма трехмерного массива a9: (2, 2, 2)

Тип данных массива a: int64
Тип данных массива a10: float64
Тип данных массива a11: float32

Массив a12 с типом данных int16:
[[0 0 0]
 [0 0 0]]

Массив a содержит целые числа: True
Массив a10 содержит числа с плавающей точкой: True

Сводная информация о массивах:
Массив a: shape=(8,), dtype=int64
Массив a5: shape=(3, 3), dtype=int64
Массив a10: shape=(3,), dtype=float64
